jobs:
  run:
    name: Run
    runs-on: ubuntu-20.04

    steps:
      - name: Startup
        uses: actions/checkout@v2
      - name: Install Deps
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Tests
        run: ./verify/build

name: Build

on:
  schedule:
    - cron: "35 2/3 * * *"
